apiVersion: apps/v1
kind: Deployment
metadata:
  name: devkit
  labels:
    app: devkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devkit
  template:
    metadata:
      labels:
        app: devkit
      annotations:
        # Verify that image is signed with Cosign
        cosign.sigstore.dev/verification: "true"
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
    spec:
      # If using a private registry
      # imagePullSecrets:
      # - name: regcred
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: devkit
        image: ghcr.io/philip-walsh/devkit:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/started
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 30
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: config
        configMap:
          name: devkit-config
          optional: true
      # Volumes if needed
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: devkit-config 